from quadrangles.diamond import *
from quadrangles.rectangle import *
from quadrangles.parallelogram import *
from quadrangles.quadrangle_type import *
from quadrangles.quadrangle import *
from quadrangles.quadrangle_type import *
from quadrangles.parallelogram import *
from quadrangles.quadrangle import *
from quadrangles.trapezoid import *
from quadrangles.rectangular_trapezoid import *
from quadrangles.equilateral_trapezoid import *